/**
 * Attribution generator (spec §12): ATTRIBUTIONS.txt and ATTRIBUTIONS.md for
 * a set of assets or an entire game project, using each license's required
 * attribution form. Unknown-license assets are included with a LOUD warning
 * block so they can never silently ship.
 */

import type { AttributionDoc, AttributionEntry, LibraryAsset } from './types';
import { LICENSE_REGISTRY, UNKNOWN_LICENSE_DEFINITION, formatAttribution, badgeFor } from './licenses/registry';

const SOURCE_NAMES: Record<string, string> = {
  polyhaven: 'Poly Haven', ambientcg: 'ambientCG', sketchfab: 'Sketchfab',
  polypizza: 'Poly Pizza', blenderkit: 'BlenderKit', opengameart: 'OpenGameArt.org',
  kenney: 'Kenney', quaternius: 'Quaternius', kaykit: 'KayKit', cgbookcase: 'CG Bookcase',
  itch: 'itch.io', cgtrader: 'CGTrader', turbosquid: 'TurboSquid', free3d: 'Free3D',
  mixamo: 'Mixamo (Adobe)', fab: 'Fab (Epic Games)', mock: 'Mock (local)',
  local: 'Local import',
};

export function entryFor(a: LibraryAsset): AttributionEntry {
  const def = LICENSE_REGISTRY[a.licenseId] ?? UNKNOWN_LICENSE_DEFINITION;
  const text = a.attributionText ?? formatAttribution(def, {
    name: a.name, creator: a.creator, url: a.sourceUrl,
  });
  return {
    assetName: a.name,
    creator: a.creator,
    source: SOURCE_NAMES[a.providerId] ?? a.providerId,
    licenseId: def.id,
    licenseName: def.name,
    licenseUrl: a.licenseUrl || def.url || undefined,
    originalUrl: a.sourceUrl,
    attributionText: text,
    requiresAttribution: def.attributionRequired || def.id === 'unknown',
  };
}

export function generateAttribution(assets: LibraryAsset[]): AttributionDoc {
  const entries = assets.map(entryFor);
  const withAttr = entries.filter((e) => e.requiresAttribution && e.licenseId !== 'unknown');
  const cc0 = entries.filter((e) => !e.requiresAttribution && e.licenseId !== 'unknown');
  const unknown = entries.filter((e) => e.licenseId === 'unknown');
  const generatedAt = new Date().toISOString();

  const txt = renderTxt({ withAttr, cc0, unknown, generatedAt });
  const md = renderMd({ withAttr, cc0, unknown, generatedAt });
  return { txt, md, entries, generatedAt };
}

function renderTxt(d: { withAttr: AttributionEntry[]; cc0: AttributionEntry[]; unknown: AttributionEntry[]; generatedAt: string }): string {
  const L: string[] = [];
  L.push('ATTRIBUTIONS');
  L.push('============');
  L.push(`Generated by Universal Game Asset Hub on ${d.generatedAt}`);
  L.push('Include the attribution sections below in your game credits / documentation.');
  L.push('');
  if (d.unknown.length) {
    L.push('!!! LICENSE UNKNOWN — DO NOT SHIP BEFORE RESOLVING !!!');
    for (const e of d.unknown) {
      L.push(`  Asset: ${e.assetName}`);
      L.push(`  Source: ${e.source}`);
      L.push(`  Original URL: ${e.originalUrl}`);
      L.push('');
    }
    L.push('');
  }
  L.push('--- Attribution required -------------------------------------------------');
  L.push('');
  if (!d.withAttr.length) L.push('(none)');
  for (const e of d.withAttr) {
    L.push(`Asset: ${e.assetName}`);
    if (e.creator) L.push(`Creator: ${e.creator}`);
    L.push(`Source: ${e.source}`);
    L.push(`License: ${e.licenseName}`);
    L.push(`Original URL: ${e.originalUrl}`);
    if (e.licenseUrl) L.push(`License URL: ${e.licenseUrl}`);
    L.push(`Required Attribution: ${e.attributionText}`);
    L.push('');
  }
  L.push('--- No attribution required (CC0 / public domain) ------------------------');
  L.push('');
  if (!d.cc0.length) L.push('(none)');
  for (const e of d.cc0) {
    L.push(`Asset: ${e.assetName}${e.creator ? ` by ${e.creator}` : ''} — ${e.licenseName} — ${e.originalUrl}`);
  }
  return L.join('\n');
}

function renderMd(d: { withAttr: AttributionEntry[]; cc0: AttributionEntry[]; unknown: AttributionEntry[]; generatedAt: string }): string {
  const L: string[] = [];
  L.push('# Attributions');
  L.push('');
  L.push(`_Generated by Universal Game Asset Hub on ${d.generatedAt}_`);
  L.push('');
  if (d.unknown.length) {
    L.push('> [!WARNING]');
    L.push('> **License unknown — do not ship before resolving:**');
    for (const e of d.unknown) L.push(`> - **${e.assetName}** (${e.source}) — <${e.originalUrl}>`);
    L.push('');
  }
  L.push('## Attribution required');
  L.push('');
  if (!d.withAttr.length) L.push('_None._');
  for (const e of d.withAttr) {
    L.push(`### ${e.assetName}`);
    L.push('');
    L.push(`- **Creator:** ${e.creator ?? '—'}`);
    L.push(`- **Source:** ${e.source}`);
    L.push(`- **License:** [${e.licenseName}](${e.licenseUrl ?? ''})`);
    L.push(`- **Original URL:** <${e.originalUrl}>`);
    L.push(`- **Required attribution:** ${e.attributionText}`);
    L.push('');
  }
  L.push('## No attribution required (CC0 / public domain)');
  L.push('');
  if (!d.cc0.length) L.push('_None._');
  else {
    L.push('| Asset | Creator | License | URL |');
    L.push('|---|---|---|---|');
    for (const e of d.cc0) L.push(`| ${e.assetName} | ${e.creator ?? '—'} | ${e.licenseName} | ${e.originalUrl} |`);
  }
  return L.join('\n');
}

export function badgeSummary(a: LibraryAsset): string {
  return badgeFor({ id: a.licenseId, commercialUse: 'allowed', attributionRequired: false, unknown: a.licenseId === 'unknown' }).label;
}
